# Generated by Django 4.2.27 on 2026-05-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
